### ISSUE TITLE
Feat 결제

### ISSUE THREAD

**Issue by Yuurim98** [Sparta-Triple/CultureTicket#6]
## Description
티켓 결제 
### Todo
- [x] 결제 생성 - 대기열 없이
- [x] 예매 생성
- [x] 결제 금액 전체 조회
- [x] 결제 내역 단일 조회

**Comment by Yuurim98** [comment]
완료
