### ISSUE TITLE
Feat: User CRUD

### ISSUE THREAD

**Issue by yshong1998** [Sparta-Triple/CultureTicket#7]
## Description
유저 CRUD 기능 구현

### Todo
- [x] 회원가입
- [x] 로그인
- [x] 유저 목록 조회
- [x] 유저 단일 조회
- [x] 유저 정보 수정
- [x] 계정 복구
- [x] 회원 탈퇴

**Comment by yshong1998** [comment]
기능 완성
